### ISSUE TITLE
Download AVSD annotations

### ISSUE THREAD

**Issue by AmingWu** [idansc/simple-avsd#2]
Hello, 

When I download AVSD annotations, it does not work. And it needs my account.

**Comment by idansc** [comment]
Hi 
It seems to work for me without any account. Can you share the exact error?

**Comment by gaopengcuhk** [comment]
<img width="1179" alt="スクリーンショット 2019-06-27 午後3 37 44" src="https://user-images.githubusercontent.com/51525797/60295383-953f3a80-98f1-11e9-92a6-ecf4955fa572.png">

**Comment by gaopengcuhk** [comment]
I meet the same error when downloading the AVSD annotations. The AVSD annotations is the same from the original author?

**Comment by idansc** [comment]
Can you try again? 

> I meet the same error when downloading the AVSD annotations. The AVSD annotations is the same from the original author?

should be fixed now, can you try again

Thanks

**Comment by gaopengcuhk** [comment]
It works. Thank you so much.
