### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by AmeenAli** [idansc/simple-avsd#4]
Hi, 
I have a question about the following line of code : 
https://github.com/idansc/simple-avsd/blob/c89f802b5ac2afb81d58c56eb4a5b642a6a48527/code/atten.py#L114
Assuming we set pairwise_flag=false, and unary_flag = true, as far as I can see from the code this will also add a pairwise potential between the passed utility and itself + unary potential for the same utility.
my question is what's the point of adding a pairwise for the utility and itself since pairwise_flag=false and unary_flag=true

**Comment by idansc** [comment]
To activate/disable self interactions use self_flag. 
Self interactions are different from the unary. In Self, each element interacts with other elements of the same modality. In Unary, the potential is based solely on the element's features. 
Please see _Entity information_ and _Entity interactions_ sections in [Factor Graph Attention](https://arxiv.org/pdf/1904.05880.pdf) for more details.
