### ISSUE TITLE
Dimensions clarification 

### ISSUE THREAD

**Issue by AmeenAli** [idansc/simple-avsd#5]
Hi,
I have two questions regarding dimensions,
**1.** Lets for example focus on the **Unary** unit, as far as I can see from the paper the input for this unit is of the shape : <img src="https://latex.codecogs.com/svg.latex?\Large&space;R^{n_{d}&#44;d}" /> where <img src="https://latex.codecogs.com/svg.latex?\Large&space;n_{d}" /> is the embeddind dimension (i.e for image or for text..) and <img src="https://latex.codecogs.com/svg.latex?\Large&space;d" /> is the number of samples and after doing the mathematics mentioned in the paper we get that the output dimension is of the shape : <img src="https://latex.codecogs.com/svg.latex?\Large&space;R^{n_{d}&#44;1}" /> which a little bit confuses me am I missing something ? otherwise how can we look at the importance of each feature for each sample? (here we got only 1 sample output).

**2.** I tried to run the following code which simply tries to add an unary attention on word embeddings of dimension 300 and I noticed that the atten class expects a tensor input of 3 dimensions (I assume the first dimension is for the batches number? fix me if i'm missing something)
``
s_output, s_lengths = nn.utils.rnn.pad_packed_sequence(s)
print(s_output.transpose(1,2).size()) # This will print : Torch.Size([48, 300, 128])
s_with_atten = self.attention(utils=[s_output.transpose(1,2).cuda()])
print(s_with_atten[0].size()) # This will print : Torch.Size([48, 300])
``
I defined self.attention as following : 
``
self.attention = Atten(util_e = [params.word_embedding_dim] , high_order_utils=[],
                            pairwise_flag = False , unary_flag=True , self_flag = False)
``
can you elaborate more on the output dimensions printed?

**Comment by idansc** [comment]
Can you specify which paper? 
1) The unary computes an importance(i.e., potential) for each spatial-feature, number of spatial features are `n`. 
2) Yes batch dimension. The output of attention unit is one attended-vector, after we aggregate utility vectors with attention weighted sum. In the paper it denotes as `a_U` where U is the utility/modality.

**Comment by AmeenAli** [comment]
I think I'm missing something here ..
let's say you pass a tensor to the attention unit (for text embeddings for example) of shape : [48 , 300 , 128] where 48 is the batch size and 300 is the embeddings dimension and 128 number of samples per batch.
now we get as output a tensor of shape : [48 , 128] my question is how can we get the attended-vector for the i'th sample in the j'th batch (which is of dimension 300) (we got [48 , 128] tensor as a return value from the forward function.. I expected to get [48 , 300 , 128]?

**Comment by idansc** [comment]
128 is the spatial dimension, for text it's length of a sentence, for image it's number of regions etc.
the batch is the number of samples. Hope this clarifies things.

**Comment by AmeenAli** [comment]
Thanks! I just confused with the dimensions.
A final question : since the forward function excepts 3 dimensional tensor [A , B , C] And A is the batch size and C is the spatial Dimension, what is B?
Thanks!

**Comment by idansc** [comment]
embedding dimension, i.e., the features representing the word/region.
